export const authLocalizationIT = {
    APP: "App",
    ACCOUNT: "Account",
    ACCOUNTS: "Account",
    ACCOUNTS_DESCRIPTION: "Passa da un account all'altro.",
    ACCOUNTS_INSTRUCTIONS: "Accedi a un altro account.",
    ADD_ACCOUNT: "Aggiungi Account",
    ADD_PASSKEY: "Aggiungi Passkey",
    ALREADY_HAVE_AN_ACCOUNT: "Hai già un account?",
    AVATAR: "Avatar",
    AVATAR_DESCRIPTION: "Clicca sull'avatar per caricare un'immagine personalizzata.",
    AVATAR_INSTRUCTIONS: "L'avatar è opzionale ma consigliato.",
    BACKUP_CODE_REQUIRED: "Codice di backup richiesto",
    BACKUP_CODES: "Codici di Backup",
    BACKUP_CODES_DESCRIPTION: "Salva questi codici in un luogo sicuro. Puoi usarli per accedere se perdi il metodo a due fattori.",
    BACKUP_CODE_PLACEHOLDER: "Codice di Backup",
    BACKUP_CODE: "Codice di Backup",
    CANCEL: "Annulla",
    CHANGE_PASSWORD: "Cambia Password",
    CHANGE_PASSWORD_DESCRIPTION: "Inserisci la password attuale e quella nuova.",
    CHANGE_PASSWORD_INSTRUCTIONS: "Usa almeno 8 caratteri.",
    CHANGE_PASSWORD_SUCCESS: "La tua password è stata cambiata.",
    CONFIRM_PASSWORD: "Conferma Password",
    CONFIRM_PASSWORD_PLACEHOLDER: "Conferma Password",
    CONFIRM_PASSWORD_REQUIRED: "La conferma della password è richiesta",
    CONTINUE_WITH_AUTHENTICATOR: "Continua con Authenticator",
    COPIED_TO_CLIPBOARD: "Copiato negli appunti",
    COPY_TO_CLIPBOARD: "Copia negli appunti",
    COPY_ALL_CODES: "Copia tutti i codici",
    CONTINUE: "Continua",
    CURRENT_PASSWORD: "Password Attuale",
    CURRENT_PASSWORD_PLACEHOLDER: "Password Attuale",
    CURRENT_SESSION: "Sessione Corrente",
    DELETE: "Elimina",
    DELETE_AVATAR: "Elimina Avatar",
    DELETE_ACCOUNT: "Elimina Account",
    DELETE_ACCOUNT_DESCRIPTION: "Rimuovi permanentemente il tuo account e tutti i contenuti. Azione irreversibile.",
    DELETE_ACCOUNT_INSTRUCTIONS: "Conferma l'eliminazione del tuo account. Azione irreversibile.",
    DELETE_ACCOUNT_VERIFY: "Controlla la tua email per verificare l'eliminazione.",
    DELETE_ACCOUNT_SUCCESS: "Il tuo account è stato eliminato.",
    DISABLE_TWO_FACTOR: "Disabilita Due Fattori",
    DISABLED_CREDENTIALS_DESCRIPTION: "Scegli un provider per accedere",
    DONT_HAVE_AN_ACCOUNT: "Non hai un account?",
    DONE: "Fatto",
    EMAIL: "Email",
    EMAIL_DESCRIPTION: "Inserisci l'indirizzo email per accedere.",
    EMAIL_INSTRUCTIONS: "Inserisci un indirizzo email valido.",
    EMAIL_IS_THE_SAME: "L'email è la stessa",
    EMAIL_PLACEHOLDER: "m@esempio.com",
    EMAIL_REQUIRED: "L'indirizzo email è richiesto",
    EMAIL_VERIFY_CHANGE: "Controlla la tua email per verificare il cambio.",
    EMAIL_VERIFICATION: "Controlla la tua email per il link di verifica.",
    ENABLE_TWO_FACTOR: "Abilita Due Fattori",
    IS_INVALID: "non è valido",
    IS_REQUIRED: "è richiesto",
    IS_THE_SAME: "è lo stesso",
    FORGOT_AUTHENTICATOR: "Authenticator dimenticato?",
    FORGOT_PASSWORD: "Password dimenticata?",
    FORGOT_PASSWORD_ACTION: "Invia link di reset",
    FORGOT_PASSWORD_DESCRIPTION: "Inserisci la tua email per reimpostare la password",
    FORGOT_PASSWORD_EMAIL: "Controlla la tua email per il link di reset.",
    FORGOT_PASSWORD_LINK: "Password dimenticata?",
    LINK: "Collega",
    MAGIC_LINK: "Magic Link",
    MAGIC_LINK_ACTION: "Invia magic link",
    MAGIC_LINK_DESCRIPTION: "Inserisci la tua email per ricevere un magic link",
    MAGIC_LINK_EMAIL: "Controlla la tua email per il magic link",
    EMAIL_OTP: "Codice Email",
    EMAIL_OTP_SEND_ACTION: "Invia codice",
    EMAIL_OTP_VERIFY_ACTION: "Verifica codice",
    EMAIL_OTP_DESCRIPTION: "Inserisci la tua email per ricevere un codice",
    EMAIL_OTP_VERIFICATION_SENT: "Controlla la tua email per il codice di verifica.",
    NAME: "Nome",
    NAME_DESCRIPTION: "Inserisci il tuo nome completo o visualizzato.",
    NAME_INSTRUCTIONS: "Massimo 32 caratteri.",
    NAME_PLACEHOLDER: "Nome",
    NEW_PASSWORD: "Nuova Password",
    NEW_PASSWORD_PLACEHOLDER: "Nuova Password",
    NEW_PASSWORD_REQUIRED: "La nuova password è richiesta",
    ONE_TIME_PASSWORD: "Password Usa e Getta",
    OR_CONTINUE_WITH: "O continua con",
    PASSKEY: "Passkey",
    PASSKEYS: "Passkeys",
    PASSKEYS_DESCRIPTION: "Gestisci le tue passkey per l'accesso sicuro.",
    PASSKEYS_INSTRUCTIONS: "Accedi in modo sicuro senza password.",
    PERSONAL_ACCOUNT: "Account Personale",
    API_KEYS: "Chiavi API",
    API_KEYS_DESCRIPTION: "Gestisci le tue chiavi API.",
    API_KEYS_INSTRUCTIONS: "Genera chiavi API per accedere programmaticamente.",
    CREATE_API_KEY: "Crea Chiave API",
    CREATE_API_KEY_DESCRIPTION: "Inserisci un nome univoco per la chiave.",
    API_KEY_NAME_PLACEHOLDER: "Nuova Chiave API",
    API_KEY_CREATED: "Chiave API Creata",
    CREATE_API_KEY_SUCCESS: "Copia la chiave e conservala al sicuro. Non sarà mostrata di nuovo.",
    NEVER_EXPIRES: "Mai",
    EXPIRES: "Scade",
    NO_EXPIRATION: "Nessuna Scadenza",
    CREATE_ORGANIZATION: "Crea Organizzazione",
    ORGANIZATION: "Organizzazione",
    ORGANIZATION_NAME: "Nome",
    ORGANIZATION_NAME_PLACEHOLDER: "Acme Inc.",
    ORGANIZATION_NAME_DESCRIPTION: "Il nome visibile dell'organizzazione.",
    ORGANIZATION_NAME_INSTRUCTIONS: "Massimo 32 caratteri.",
    ORGANIZATION_SLUG: "URL Slug",
    ORGANIZATION_SLUG_DESCRIPTION: "Namespace URL dell'organizzazione.",
    ORGANIZATION_SLUG_INSTRUCTIONS: "Massimo 48 caratteri.",
    ORGANIZATION_SLUG_PLACEHOLDER: "acme-inc",
    CREATE_ORGANIZATION_SUCCESS: "Organizzazione creata con successo",
    PASSWORD: "Password",
    PASSWORD_PLACEHOLDER: "Password",
    PASSWORD_REQUIRED: "Password richiesta",
    PASSWORDS_DO_NOT_MATCH: "Le password non corrispondono",
    PROVIDERS: "Provider",
    PROVIDERS_DESCRIPTION: "Collega il tuo account a un servizio esterno.",
    RECOVER_ACCOUNT: "Recupera Account",
    RECOVER_ACCOUNT_ACTION: "Recupera account",
    RECOVER_ACCOUNT_DESCRIPTION: "Inserisci un codice di backup per accedere",
    REMEMBER_ME: "Ricordami",
    RESEND_CODE: "Invia di nuovo",
    RESEND_VERIFICATION_EMAIL: "Invia di nuovo email di verifica",
    RESET_PASSWORD: "Reimposta Password",
    RESET_PASSWORD_ACTION: "Salva nuova password",
    RESET_PASSWORD_DESCRIPTION: "Inserisci la tua nuova password",
    RESET_PASSWORD_SUCCESS: "Password reimpostata con successo",
    REQUEST_FAILED: "Richiesta fallita",
    REVOKE: "Revoca",
    DELETE_API_KEY: "Elimina Chiave API",
    DELETE_API_KEY_CONFIRM: "Sei sicuro di voler eliminare questa chiave API?",
    API_KEY: "Chiave API",
    SIGN_IN: "Accedi",
    SIGN_IN_ACTION: "Accedi",
    SIGN_IN_DESCRIPTION: "Inserisci la tua email per accedere",
    SIGN_IN_USERNAME_DESCRIPTION: "Inserisci username o email per accedere",
    SIGN_IN_WITH: "Accedi con",
    SIGN_OUT: "Esci",
    SIGN_UP: "Registrati",
    SIGN_UP_ACTION: "Crea account",
    SIGN_UP_DESCRIPTION: "Inserisci i tuoi dati per creare un account",
    SIGN_UP_EMAIL: "Controlla la tua email per il link di verifica.",
    SESSIONS: "Sessioni",
    SESSIONS_DESCRIPTION: "Gestisci le sessioni attive.",
    SET_PASSWORD: "Imposta Password",
    SET_PASSWORD_DESCRIPTION: "Clicca per ricevere un'email per impostare la password.",
    SETTINGS: "Impostazioni",
    SAVE: "Salva",
    SECURITY: "Sicurezza",
    SWITCH_ACCOUNT: "Cambia Account",
    TRUST_DEVICE: "Fidati di questo dispositivo",
    TWO_FACTOR: "Due Fattori",
    TWO_FACTOR_ACTION: "Verifica codice",
    TWO_FACTOR_DESCRIPTION: "Inserisci la password usa e getta per continuare",
    TWO_FACTOR_CARD_DESCRIPTION: "Aggiungi un livello di sicurezza extra.",
    TWO_FACTOR_DISABLE_INSTRUCTIONS: "Inserisci la password per disabilitare 2FA.",
    TWO_FACTOR_ENABLE_INSTRUCTIONS: "Inserisci la password per abilitare 2FA.",
    TWO_FACTOR_ENABLED: "Autenticazione a due fattori abilitata",
    
    // Error codes
    USER_NOT_FOUND: "Utente non trovato",
    INVALID_EMAIL_OR_PASSWORD: "Email o password non validi",
    INVALID_PASSWORD: "Password non valida",
    PASSWORD_TOO_SHORT: "Password troppo corta",
    PASSWORD_TOO_LONG: "Password troppo lunga",
    USER_ALREADY_EXISTS: "Utente già esistente",
    FAILED_TO_CREATE_USER: "Impossibile creare l'utente",
    FAILED_TO_CREATE_SESSION: "Impossibile creare la sessione",
    INVALID_EMAIL: "Email non valida",
    EMAIL_NOT_VERIFIED: "Email non verificata",
    TOO_MANY_ATTEMPTS: "Troppi tentativi",
    UNKNOWN_ERROR: "Qualcosa è andato storto"
};
